name: ciipro-bare
channels:
  - rdkit
  - anaconda
  - defaults
dependencies:
  - bokeh=1.2.0
  - flask=1.1.1
  - flask-login=0.4.1
  - h5py=2.9.0
  - keras=2.1.2
  - numpy=1.15.4
  - pandas=0.23.4
  - pip=19.1.1
  - pymongo=3.8.0
  - python=3.6.8
  - rdkit=2019.03.3.0
  - requests=2.22.0
  - scikit-learn=0.19.0
  - scipy=1.1.0
  - sqlalchemy=1.3.5
  - flask-sqlalchemy
  - sqlite=3.29.0
  - gunicorn

